### ISSUE TITLE
recommended-workbooks endpoint returning not found

### ISSUE THREAD

**Issue by philip-khor** [wjsutton/tableau_public_api#2]
Example provided now returns 

```
{
    "path": "/apis/bff/workbooks/v1/RunningforOlympicGold/recommended-workbooks",
    "error": "Not Found",
    "timestamp": 1728268447121,
    "status": 404
}
```

**Comment by wjsutton** [comment]
Thanks for flagging, it looks like the related workbooks api is now running v2 version, docs updated with example: 

https://public.tableau.com/public/apis/bff/workbooks/v2/RunningforOlympicGold/recommended-workbooks?count=20
